const ENABLE_CHAT_UPLOAD = process.env.ENABLE_CHAT_UPLOAD || true;
const UPLOAD_MAX_FILESIZE = process.env.UPLOAD_MAX_FILESIZE;
const ADMIN_API_URL = process.env.ADMIN_API_URL;

const AWS_ACCESS_KEY_ID = process.env.AWS_ACCESS_KEY_ID;
const AWS_SECRET_ACCESS_KEY = process.env.AWS_SECRET_ACCESS_KEY;
const AWS_DEFAULT_REGION = process.env.AWS_DEFAULT_REGION;
const AWS_BUCKET = process.env.AWS_BUCKET;
const AWS_ENDPOINT = process.env.AWS_ENDPOINT;
const UPLOADER_AWS_SIGNED_URL_EXPIRATION = parseInt(process.env.UPLOADER_AWS_SIGNED_URL_EXPIRATION || "60")

const S3_CDN_ACCESS_KEY_ID = process.env.S3_CDN_ACCESS_KEY_ID;
const S3_CDN_SECRET_ACCESS_KEY = process.env.S3_CDN_SECRET_ACCESS_KEY;
const S3_CDN_USER_REFS_BUCKET = process.env.S3_CDN_USER_REFS_BUCKET;
const S3_CDN_BOT_GENS_BUCKET = process.env.S3_CDN_BOT_GENS_BUCKET;
const S3_CDN_ENDPOINT = process.env.S3_CDN_ENDPOINT;
const S3_CDN_REGION = process.env.S3_CDN_REGION;

const S3_CDN_USER_REFS_PUBLIC_URL = process.env.S3_CDN_USER_REFS_PUBLIC_URL;
const S3_CDN_BOT_GENS_PUBLIC_URL = process.env.S3_CDN_BOT_GENS_PUBLIC_URL;
const REDIS_HOST = process.env.REDIS_HOST;
const REDIS_PORT = process.env.REDIS_PORT || "6379";
const REDIS_DB_NUMBER = process.env.REDIS_DB_NUMBER;
const REDIS_PASSWORD = process.env.REDIS_PASSWORD;

const UPLOADER_URL = process.env.UPLOADER_URL;
const PLAY_URL = process.env.PLAY_URL;

export const ALLOWED_CORS_ORIGIN = process.env.ALLOWED_CORS_ORIGIN || PLAY_URL || "*";
export const DEBUG_ERROR_MESSAGES = process.env.DEBUG_ERROR_MESSAGES || "";

export const SENTRY_DSN = process.env.SENTRY_DSN_UPLOADER;
export const SENTRY_RELEASE = process.env.SENTRY_RELEASE;
export const SENTRY_ENVIRONMENT = process.env.SENTRY_ENVIRONMENT;
export const SENTRY_TRACES_SAMPLE_RATE = parseFloat(process.env.SENTRY_TRACES_SAMPLE_RATE || "0.1");

export {
    ENABLE_CHAT_UPLOAD,
    UPLOAD_MAX_FILESIZE,
    ADMIN_API_URL,
    UPLOADER_URL,
    PLAY_URL,

    AWS_ACCESS_KEY_ID,
    AWS_SECRET_ACCESS_KEY,
    AWS_DEFAULT_REGION,
    AWS_BUCKET,
    AWS_ENDPOINT,
    UPLOADER_AWS_SIGNED_URL_EXPIRATION,

    REDIS_HOST,
    REDIS_PORT,
    REDIS_DB_NUMBER,
    REDIS_PASSWORD,

    S3_CDN_ACCESS_KEY_ID,
    S3_CDN_SECRET_ACCESS_KEY,
    S3_CDN_USER_REFS_BUCKET,
    S3_CDN_BOT_GENS_BUCKET,
    S3_CDN_ENDPOINT,
    S3_CDN_REGION,
    S3_CDN_USER_REFS_PUBLIC_URL,
    S3_CDN_BOT_GENS_PUBLIC_URL,
};
